### PR TITLE
remove debugger

### PR DESCRIPTION
**Pull request by NarHakobyan**
remove debugger; to be able to debug the serverless app
Problem is the debugger is stopping in each request

### CODE REVIEW

**Comment by fabiomcosta** [comment]
Hi @NarHakobyan !
Thank you for using and contributing back to `thebugger`!
We can't remove that `debugger` statement because it's part of this library's functionality.

One alternative solution to only opening the inspector is to create a new public function that would only do that and `thebugger` would call it.

`thebugger.open()` - only opens the inspector
`thebugger()` - calls `thebugger.open()` and keeps the `debugger` right after that.

Can you better explain the problem you're having?

**Comment by NarHakobyan** [comment]
Hi @fabiomcosta , thanks for the answer.
Each time when calling serverless framework (AWS lambda) action it's running all modules (is not cached, and not running a server like a monolith app) 
and each time need to open debugger and click PLAY button and resume debugging process
I have tested without debugger and it's worked.

**Comment by fabiomcosta** [comment]
@NarHakobyan, sorry I'm still a bit confused about your use case, I guess because I haven't used AWS lambda in the past, so bear with me here :/
How is `thebugger` being useful to you without a `debugger` statement? I mean, if you don't need to debug, why are you even calling `thebugger`?

**Comment by NarHakobyan** [comment]
I am using thebugger, but in each API request I am resuming debugger, because it's stopping in this line (serverless loading all files in each request)

**Comment by fabiomcosta** [comment]
Sounds like this conversation would be more productive via messages.
Can you add me on messenger? https://facebook.com/fabs

**Comment by fabiomcosta** [comment]
@NarHakobyan do you have another preferred channel to talk more quickly?

**Pull request closed without merging**
